# Makefile #
#
all: ppa ppb ppc ppd ppe

ppa: ppa.c
	cc -Wall ppa.c -o ppa -pthread

ppb: ppb.c
	cc -Wall ppb.c -o ppb -pthread

ppc: ppc.c
	cc -Wall ppc.c -o ppc -pthread

ppd: ppd.c
	cc -Wall ppd.c -o ppd -pthread

ppe: ppe.c
	cc -Wall ppe.c -o ppe -pthread


clean:
	rm -f ppa ppb ppc ppd ppe
