# Project: timer_io
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o timer_tools.o udp_remote.o
LINKOBJ  = main.o timer_tools.o udp_remote.o
LIBS     = -L"C:/ajs/Sist_e_Autom_2016_17/Lab/Lab9_Simple_C_Sim/simplecsim_deploy201617/Dev-Cpp 5.11 TDM-GCC x64 4.9.2 Portable/Dev-Cpp/MinGW64/lib" -L"C:/ajs/Sist_e_Autom_2016_17/Lab/Lab9_Simple_C_Sim/simplecsim_deploy201617/Dev-Cpp 5.11 TDM-GCC x64 4.9.2 Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -lwsock32 -g3
INCS     = -I"C:/ajs/Sist_e_Autom_2016_17/Lab/Lab9_Simple_C_Sim/simplecsim_deploy201617/Dev-Cpp 5.11 TDM-GCC x64 4.9.2 Portable/Dev-Cpp/MinGW64/include" -I"C:/ajs/Sist_e_Autom_2016_17/Lab/Lab9_Simple_C_Sim/simplecsim_deploy201617/Dev-Cpp 5.11 TDM-GCC x64 4.9.2 Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/ajs/Sist_e_Autom_2016_17/Lab/Lab9_Simple_C_Sim/simplecsim_deploy201617/Dev-Cpp 5.11 TDM-GCC x64 4.9.2 Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/ajs/Sist_e_Autom_2016_17/Lab/Lab9_Simple_C_Sim/simplecsim_deploy201617/Dev-Cpp 5.11 TDM-GCC x64 4.9.2 Portable/Dev-Cpp/MinGW64/include" -I"C:/ajs/Sist_e_Autom_2016_17/Lab/Lab9_Simple_C_Sim/simplecsim_deploy201617/Dev-Cpp 5.11 TDM-GCC x64 4.9.2 Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/ajs/Sist_e_Autom_2016_17/Lab/Lab9_Simple_C_Sim/simplecsim_deploy201617/Dev-Cpp 5.11 TDM-GCC x64 4.9.2 Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/ajs/Sist_e_Autom_2016_17/Lab/Lab9_Simple_C_Sim/simplecsim_deploy201617/Dev-Cpp 5.11 TDM-GCC x64 4.9.2 Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = simpleCsim.exe
CXXFLAGS = $(CXXINCS) -Wall -g3
CFLAGS   = $(INCS) -Wall -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

timer_tools.o: timer_tools.c
	$(CC) -c timer_tools.c -o timer_tools.o $(CFLAGS)

udp_remote.o: udp_remote.c
	$(CC) -c udp_remote.c -o udp_remote.o $(CFLAGS)
